### ISSUE TITLE
Switching to "Nifty Stopwatch" tries to equip "Winterfall Firewater"

### ISSUE THREAD

**Issue by Horiwix** [RagedUnicorn/wow-classic-gearmenu#27] opened 2019-10-19 16:00 UTC
* Steps to reproduce:
1. Have Nifty Stopwatch and Winterfall Firewater in your inventory
2. Try to equip Nifty through gearmenu
3. Gearmenu tries to equip Winterfall Firewater. Error pops up - "This item cannot be equipped"

I tried to move the potion to other slots in the inventory - still tries to equip it. After I banked the potion, it was able to equip Nifty.

(Also using Bagnon addon; not sure if that impacts it)

![image](https://user-images.githubusercontent.com/47057857/67147964-96321880-f2a2-11e9-9f1d-137415f7a346.png)

edit: using the version v1.0.1 from "releases" page

**Comment by RagedUnicorn** [comment] 2019-10-21 08:07
Hi @Horiwix,

I tried to reproduce this but was unable so far. I usually always carry the Nifty Stopwatch and some Winterfall Firewater with me but never saw this problem. It is also strange that it is only for a specific item in your case.

Usually addons work with the id of an item. What is suspicious about those 2 items is that they have a "similar" id.

Winterfall Firewater:

https://classic.wowhead.com/item=12820/winterfall-firewater

Nifty Stopwatch:

https://classic.wowhead.com/item=2820/nifty-stopwatch

As you can see the only difference in the id is the 1 in the beginning.

Can you try to deactivate all of the addons and only run Gearmenu? Are you still able to reproduce the issue then?

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment] 2019-10-29 20:44
Hi @Horiwix 

Closing this ticket because there was no further activity and I was unable to reproduce the issue. Feel free to reopen if you have more information about the issue.

Cheers,
RagedUnicorn

**Closed by RagedUnicorn** 2019-10-29 20:44 UTC
Labels: bug
