### ISSUE TITLE
Suggestion: Colored border for specific items

### ISSUE THREAD

**Issue by Calzeru** [RagedUnicorn/wow-classic-gearmenu#45] opened 2020-01-14 19:56 UTC
Hello

First of all, thanks for creating this addon. Absolutely love it.

Onto my suggestion.
After acquiring my second pairs of Giantstalker's gloves and boots I've come across the (small) issue that the items have the same icon. This makes it difficult to look at a quick glance whether I have my mount speed or agility enchanted gear equipped.

One suggestion is to color code the items with different borders

For example:
Orange border - Mount speed. 
Green border - Agility 
https://imgur.com/rfPoh40

I have no idea how time consuming or difficult it would be to implement such a change, but it would definitely be a nice QoL change.

**Comment by RagedUnicorn** [comment] 2020-01-17 08:43
Hi @Calzeru 

I understand your issue. I would say the visual part is fairly easy to do. The problem is more in the way of finding out what kind of enchant is on the item and the work of having this for all of the possible enchants. I will look into this when I find time but won't promise anything :) Thanks for your input though!

For now I would definitely make sure that you have tooltips enable then you can at least see which pair your are currently hovering over.

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment] 2021-12-20 16:45
Cleanup - Closing this

**Closed by RagedUnicorn** 2021-12-20 16:45 UTC
Labels: enhancement
