### ISSUE TITLE
Reload/Restart of game Client resets gearmenu position

### ISSUE THREAD

**Issue by SlizeTBC** [RagedUnicorn/wow-classic-gearmenu#24] opened 2019-10-04 21:33 UTC
Hi,

as the title says, I have a "bug" which makes my gearmenu settings i made get deleted after every restart of the game.

Somehow even after reloading my UI.

Would appreciate any help, Thanks.

**Comment by RagedUnicorn** [comment] 2019-10-10 10:29
Hi @SlizeTBC,

This sounds strange. Can you give me some more details about your installation. Did you download a release version from here - https://github.com/RagedUnicorn/wow-classic-gearmenu/releases ?

Did you check whether there is a file created for your character in your `WTF` folder and whether it has any contents? Also note that some settings such as keybinds are not saved when you forceclose the WoW client. As a rule of thumb if you do changes that you want saved at least do a logout to your character screen. At this point wow writes files and thus saves settings.

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment] 2019-10-24 07:47
Hi @SlizeTBC,

Going to close this because I didn't hear back from you. Feel free to reopen or create a new ticket if this problem persists or you have more information for me to reproduce this.

Cheers,
Ragedunicorn

**Closed by RagedUnicorn** 2019-10-24 07:47 UTC
Labels: bug
