### ISSUE TITLE
UI crash

### ISSUE THREAD

**Issue by brett1337** [RagedUnicorn/wow-classic-gearmenu#59] opened 2020-03-26 16:50 UTC
Many people I know are getting full UI crashes in Arathi Basin, where the UI completely disappears. We have ruled out the usual suspects addons and it appears to be directly related to Gear Menu. It is seemingly random when it occurs but it is always Arathi Basin.

**Comment by RagedUnicorn** [comment] 2020-03-28 17:17
Hi @brett1337 

Definitely need to give me more information about this issue for me to work on that.

I play Arathi Basin myself and never saw an issue like. Was there a lua error? Does a simple reload of the ui fix the issue? Is it happen often or in a specific case? Where you able to reproduce this with all other addons disabled and only GearMenu active?

Regards,
RagedUnicorn

**Comment by brett1337** [comment] 2020-03-29 00:49
There is no lua error. a reload of the ui does fix it for a couple BGs. it happens itermitently after a certain amount of pvping like 2 BGs worth. I ahve not tried reproducing this with all other addons disabled. It probably is a weird addon interaction and that makes it really hard to figure out. This was more of a desperate attempt to see if you could repro the bug. Thanks for responding.

**Comment by HiImRob** [comment] 2020-04-10 12:33
I am also experiencing  the same phenomenon. Let me try to explain as much as possible while I am not able to deterministically reproduce this issue. 

I make excessive use of your addon by letting it auto-swap multiple items back and forth with individual timers after usage. After one or two hours of playing this issue happens. It is connected to the switch of items after I leave combat. 

As @brett1337 described, the complete UI disappears. Sometimes I can make the UI reappear when I am pressing my "open bag" button. This works as some kind of toggle, hence when I press the button again, the UI disappears again.

I can image some sort of overflow is happening within the memory, but then again no error or anything occurs and after /reloadui it works perfectly again.

**Comment by RagedUnicorn** [comment] 2021-05-16 19:04
Closing this because I was never able to reproduce it. However there where a lot of changes in the new version 2.0. I fixed a lot of bad behavior regarding cooldowns and I could image that something like that could happen with extensive use.

Please let me know if this can be reproduced with the newest version.

Cheers
RagedUnicorn

**Closed by RagedUnicorn** 2021-05-16 19:04 UTC
Labels: question
